/**
 * AdConcept Types
 *
 * Type definitions for competitor ad analysis in Ad Recreation Module.
 * This is the exact schema enforced on Claude Vision's JSON output.
 */

// ═══════════════════════════════════════════════════════════
// Concept Zone - Individual zone/section in ad layout
// ═══════════════════════════════════════════════════════════

/**
 * Allowed content_type values (controlled vocabulary)
 */
export type ConceptContentType =
    | 'headline'
    | 'subheadline'
    | 'body'
    | 'feature_badges'
    | 'product_image'
    | 'image'
    | 'testimonial_overlay'
    | 'composite_product_social_proof'
    | 'cta_button'
    | 'cta_subtext'
    | 'social_proof_line'
    | 'background_only'
    | 'logo'
    | 'ui_element';

/**
 * ConceptZone - A spatial zone extracted by Claude Vision
 * Coordinates are ABSOLUTE PIXEL values based on real image dimensions.
 */
export interface ConceptZone {
    id: string;
    y_start: number;
    y_end: number;
    height_percent?: number;           // 0-100, percentage of total image height
    content_type: ConceptContentType;
    structural_role?: string;          // e.g. "primary_headline", "hero_product_area"
    typography_style?: string;         // e.g. "Bold Sans-Serif White"
    description?: string;              // describe the PATTERN, not competitor content
}

// ═══════════════════════════════════════════════════════════
// Visual Style - Background configuration
// ═══════════════════════════════════════════════════════════

export interface VisualBackground {
    type: 'solid_color' | 'image' | 'gradient' | 'textured';
    hex: string | null;
}

// ═══════════════════════════════════════════════════════════
// Content Pattern - Marketing angle structure
// ═══════════════════════════════════════════════════════════

export interface ContentPattern {
    hook_type: string;
    narrative_structure: string;
    cta_style: string;
    requires_product_image: boolean;
}

// ═══════════════════════════════════════════════════════════
// Image Metadata (new — from strict extraction)
// ═══════════════════════════════════════════════════════════

export interface ConceptImageMeta {
    width: number;
    height: number;
    aspect_ratio: number;
    orientation: 'vertical' | 'square' | 'horizontal';
}

// ═══════════════════════════════════════════════════════════
// CTA Structure (new — from strict extraction)
// ═══════════════════════════════════════════════════════════

export interface ConceptCtaStructure {
    has_cta_button: boolean;
    has_cta_subtext: boolean;
}

// ═══════════════════════════════════════════════════════════
// Ad Concept Analysis - Full analysis structure
// ═══════════════════════════════════════════════════════════

/**
 * AdConceptAnalysis - Visual DNA extracted by Claude Vision
 * Used to recreate the ad structure for a different brand.
 */
export interface AdConceptAnalysis {
    layout: {
        type: string;
        format?: string;               // e.g. "9:16", "1:1" — may be auto-detected
        zones: ConceptZone[];
    };
    visual_style: {
        mood?: string;                  // kept for backward compatibility
        background: VisualBackground;
        overlay?: string;
        // New strict fields (optional for backward compat)
        dominant_background_color?: string;
        product_position?: string;
        lighting_style?: string;
        ui_elements_present?: boolean;
    };
    content_pattern: ContentPattern;

    // ─── Auto-generated by Claude during analysis ────────
    concept_name?: string;              // e.g. "Split Screen Benefits Ad"
    concept_tags?: string[];            // e.g. ["notes_app", "split_screen", "editorial"]

    // ─── New strict extraction fields (optional) ─────────
    image_meta?: ConceptImageMeta;
    cta_structure?: ConceptCtaStructure;
}

